version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: session-demo
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: session
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-session-data:/var/lib/mysql
    networks:
      - spring-net

  redis:
    image: redis:7
    container_name: session-demo-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]  # 데이터 영속화를 위한 설정
    volumes:
      - redis-session-data:/data
    networks:
      - spring-net

volumes:
  mysql-session-data:
  redis-session-data:

networks:
  spring-net:
