server:
  port: 8081

spring:
  application:
    name: session
  datasource:
    url: jdbc:mysql://localhost:3306/session?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update # create-drop / create / update / validate / none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis
    timeout: 30m